spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: calc
    password: root
    url: jdbc:mysql://localhost:3306/calc?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true